logging:
  level:
    br.com.dbccompany.votacaocooperado: TRACE
    org.springframework: INFO
    com.zaxxer.hikari: INFO

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:${PATH_DB}/votacao-cooperado-h2-db;MODE=Oracle;INIT=RUNSCRIPT FROM 'classpath:schema.sql'
    username: ${USERNAME_H2}
    password: ${PASSWORD_H2}
  jpa:
    show-sql: false

client:
  usuario:
    url: ${URL_USUARIO_CLIENT}