server.port=8081
spring.datasource.url=jdbc:h2:file:./votacao-cooperado-h2-db
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.allow-bean-definition-overriding=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
springdoc.swagger-ui.path:/swagger-ui.html